config/routes.rb
Rails.application.routes.draw do
 resources :calculators, only: [:index, :new, :create, :show]
 get 'calculators/index'
 root "calculators#new"
 post 'calculate', to: 'calculators#calculate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculator.rb
class Calculator
  def add(numbers)
    return 0 if numbers.empty?

    delimiter = ","
    if numbers.start_with?("//")
      parts = numbers.split("\n", 2)
      delimiter = parts[0][2..-1]
      numbers = parts[1]
    end

    numbers = numbers.gsub("\n", delimiter)
    number_list = numbers.split(delimiter).map(&:to_i)
    
    negatives = number_list.select { |n| n < 0 }
    if negatives.any?
      raise "negative numbers not allowed: #{negatives.join(', ')}"
    end

    number_list.sum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  def index    
  end
  def new
  end
  def create
    input = params[:calculator][:input]
    result = Calculator.add(input)
    @calculator = Calculator.create(input: input, result: result)
    render :show
  rescue => e
    @error = e.message
    render :new
  end

  def show
    @calculator = Calculation.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculators_helper.rb
module CalculatorsHelper
end

app/views/calculators/index.html.erb
<!-- app/views/calculators/index.html.erb -->
<h1>String Calculator</h1>
<%= form_with url: calculate_path, method: :post, local: true do %>
  <%= submit_tag "Calculate" %>
<% end %>
  <div>
    <%= label_tag :numbers, "Enter numbers:" %>
    <%= text_area_tag :numbers %>
  </div>
 <%#  <%= submit_tag "Calculate" %>
<%# <% end %> %> %>

<% if @result %>
  <p>Result: <%= @result %></p>
<% end %>

app/views/calculators/new.html.erb
<%= form_with model: Calculation.new, url: calculations_path, local: true do |form| %>
  <% if @error %>
    <p><%= @error %></p>
  <% end %>
  <div>
    <%= form.label :input, "Enter numbers" %>
    <%= form.text_field :input %>
  </div>
  <div>
    <%= form.submit "Calculate" %>
  </div>
<% end %>

app/views/calculators/show.html.erb
<p>Input: <%= @calculation.input %></p>
<p>Result: <%= @calculation.result %></p>
<%= link_to 'New Calculation', new_calculation_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StringCalculator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>